runtime: custom
env: flex

# app engine deploys on compute engine instances
# this tells it what size you want
# F1 is the smallest and default size
# you can increase this later if needed
instance_class: F1

# app engine will automatically create more instances 
# to keep your app up if there is sudden high traffic
# this makes sure app engine doesn't create more than
# you're comfortable with
automatic_scaling:
  max_num_instances: 1


